'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class Conectados
        Inherits XPLiteObject
        Dim fIdcon As Integer
        <Key(True)>
        Public Property Idcon() As Integer
            Get
                Return fIdcon
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Idcon", fIdcon, value)
            End Set
        End Property
        Dim fEquipo As String
        <Size(90)>
        Public Property Equipo() As String
            Get
                Return fEquipo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Equipo", fEquipo, value)
            End Set
        End Property
        Dim fUltimaconexion As String
        <Size(200)>
        Public Property Ultimaconexion() As String
            Get
                Return fUltimaconexion
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Ultimaconexion", fUltimaconexion, value)
            End Set
        End Property
        Dim fLogin As String
        <Size(80)>
        Public Property Login() As String
            Get
                Return fLogin
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Login", fLogin, value)
            End Set
        End Property
    End Class

End Namespace
