'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class Equipos
        Inherits XPLiteObject
        Dim fID As Integer
        <Key(True)>
        Public Property ID() As Integer
            Get
                Return fID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("ID", fID, value)
            End Set
        End Property
        Dim fNombreEquipo As String
        <Size(255)>
        Public Property NombreEquipo() As String
            Get
                Return fNombreEquipo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NombreEquipo", fNombreEquipo, value)
            End Set
        End Property
        Dim fUsuario As String
        <Size(255)>
        Public Property Usuario() As String
            Get
                Return fUsuario
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Usuario", fUsuario, value)
            End Set
        End Property
        Dim fActualizo As Integer
        Public Property Actualizo() As Integer
            Get
                Return fActualizo
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Actualizo", fActualizo, value)
            End Set
        End Property
    End Class

End Namespace
