'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class Impuestos
        Inherits XPLiteObject
        Dim fIdImpuesto As Integer
        <Key(True)>
        Public Property IdImpuesto() As Integer
            Get
                Return fIdImpuesto
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdImpuesto", fIdImpuesto, value)
            End Set
        End Property
        Dim fIVA As Decimal
        Public Property IVA() As Decimal
            Get
                Return fIVA
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("IVA", fIVA, value)
            End Set
        End Property
        Dim fDetalle As String
        <Size(255)>
        Public Property Detalle() As String
            Get
                Return fDetalle
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Detalle", fDetalle, value)
            End Set
        End Property
        Dim fMultiplo As Decimal
        Public Property Multiplo() As Decimal
            Get
                Return fMultiplo
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Multiplo", fMultiplo, value)
            End Set
        End Property
    End Class

End Namespace
