'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class ListaTablas
        Inherits XPLiteObject
        Dim fid As Integer
        <Key(True)>
        Public Property id() As Integer
            Get
                Return fid
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("id", fid, value)
            End Set
        End Property
        Dim fTabla As String
        <Size(255)>
        Public Property Tabla() As String
            Get
                Return fTabla
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Tabla", fTabla, value)
            End Set
        End Property
    End Class

End Namespace
