'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class ProductosProduccion
        Inherits XPLiteObject
        Dim fid As Integer
        <Key(True)>
        Public Property id() As Integer
            Get
                Return fid
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("id", fid, value)
            End Set
        End Property
        Dim fcodigo As Integer
        Public Property codigo() As Integer
            Get
                Return fcodigo
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("codigo", fcodigo, value)
            End Set
        End Property
        Dim fCodigoAlfa As String
        <Size(50)>
        Public Property CodigoAlfa() As String
            Get
                Return fCodigoAlfa
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CodigoAlfa", fCodigoAlfa, value)
            End Set
        End Property
        Dim fDetalle As String
        <Size(SizeAttribute.Unlimited)>
        Public Property Detalle() As String
            Get
                Return fDetalle
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Detalle", fDetalle, value)
            End Set
        End Property
        Dim fRubro As String
        <Size(50)>
        Public Property Rubro() As String
            Get
                Return fRubro
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Rubro", fRubro, value)
            End Set
        End Property
    End Class

End Namespace
