'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class Proyectos
        Inherits XPLiteObject
        Dim fIdProyecto As Integer
        <Key(True)>
        Public Property IdProyecto() As Integer
            Get
                Return fIdProyecto
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdProyecto", fIdProyecto, value)
            End Set
        End Property
        Dim fNombreProyecto As String
        <Size(255)>
        Public Property NombreProyecto() As String
            Get
                Return fNombreProyecto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NombreProyecto", fNombreProyecto, value)
            End Set
        End Property
        Dim fSectorProyecto As String
        <Size(80)>
        Public Property SectorProyecto() As String
            Get
                Return fSectorProyecto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SectorProyecto", fSectorProyecto, value)
            End Set
        End Property
    End Class

End Namespace
