'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class SubRubros
        Inherits XPLiteObject
        Dim fIdSubRubro As Integer
        <Key(True)>
        Public Property IdSubRubro() As Integer
            Get
                Return fIdSubRubro
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdSubRubro", fIdSubRubro, value)
            End Set
        End Property
        Dim fSubRubro As String
        <Size(255)>
        Public Property SubRubro() As String
            Get
                Return fSubRubro
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SubRubro", fSubRubro, value)
            End Set
        End Property
    End Class

End Namespace
