'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    <Persistent("TOTALES IDPEDIDO")>
    Partial Public Class TOTALESIDPEDIDO
        Inherits XPLiteObject
        Dim fIdPedido As Integer
        <Key()>
        Public Property IdPedido() As Integer
            Get
                Return fIdPedido
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdPedido", fIdPedido, value)
            End Set
        End Property
        Dim ftotal As Decimal
        Public Property total() As Decimal
            Get
                Return ftotal
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("total", ftotal, value)
            End Set
        End Property
    End Class

End Namespace
