'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace MontagneAdministracion

    Partial Public Class VistaProductos
        Inherits XPLiteObject
        Dim fRazonSocial As String
        <Size(80)>
        Public Property RazonSocial() As String
            Get
                Return fRazonSocial
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RazonSocial", fRazonSocial, value)
            End Set
        End Property
        Dim fProducto As String
        Public Property Producto() As String
            Get
                Return fProducto
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Producto", fProducto, value)
            End Set
        End Property
        Dim fPrecioUnitario As Decimal
        Public Property PrecioUnitario() As Decimal
            Get
                Return fPrecioUnitario
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("PrecioUnitario", fPrecioUnitario, value)
            End Set
        End Property
        Dim fMarca As String
        <Size(80)>
        Public Property Marca() As String
            Get
                Return fMarca
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Marca", fMarca, value)
            End Set
        End Property
        Dim fFechaModificacion As DateTime
        Public Property FechaModificacion() As DateTime
            Get
                Return fFechaModificacion
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FechaModificacion", fFechaModificacion, value)
            End Set
        End Property
        Dim fRow As Long
        <Key()>
        Public Property Row() As Long
            Get
                Return fRow
            End Get
            Set(ByVal value As Long)
                SetPropertyValue(Of Long)("Row", fRow, value)
            End Set
        End Property
        Dim fIdProveedor As Integer
        Public Property IdProveedor() As Integer
            Get
                Return fIdProveedor
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("IdProveedor", fIdProveedor, value)
            End Set
        End Property
    End Class

End Namespace
